quarkus.http.port=8084

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=oracle123

quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/testdb

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.path=/openapi